### ISSUE TITLE
Update preview automatically

### ISSUE THREAD

**Issue by zeke** [gmattie/Data-Pixels#2]
Cool app!

I keep clicking the "run" button. Maybe that's not necessary though. Couldn't the preview update any time a change is made to the code?

**Comment by gmattie** [comment]
Thanks, zeke :)

Initially, I planned to have the program automatically update, as you suggested, but in doing so I didn't know how to achieve an appropriate user experience in regards to simultaneously displaying a user's compile time errors, so in the end I just decided to simply mirror the functionality of jsfiddle and other standard IDEs.

**Comment by zeke** [comment]
> simultaneously displaying a user's compile time errors

Yeah I was thinking about that. What if you just only display the graphic when the code is valid?

**Comment by gmattie** [comment]
That could certainly be added as an optional feature.

**Comment by gmattie** [comment]
Hey @zeke 

I just published a new release for **[Data Pixels Playground v1.1.0](https://github.com/gmattie/Data-Pixels/releases/tag/1.1.0)** which features an optional setting for updating the preview automatically.

If you have a chance check it out and let me know what you think.  :-)

**Comment by zeke** [comment]
Thanks for the followup. :)
