### ISSUE TITLE
how does this work

### ISSUE THREAD

**Issue by SHADOWELITE7** [gmattie/Data-Pixels#5]

**Comment by gmattie** [comment]
All the main logic is contained within **[DataPixels.js](https://github.com/gmattie/Data-Pixels/blob/master/resources/source/js/dataPixels/DataPixels.js)**

First, there are several error checks to make sure that the supplied _pixelData_ argument is valid.  If the validation check passes, the arrays of color descriptions within the _pixelData_ array argument are processed into either 24bit or 32bit colors using a **[Uint8ClammpedArray](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray)**.  Finally, an HTMLImageElement or a 2D HTMLCanvasElement can be created by passing the processed color data to an **[ImageData](https://developer.mozilla.org/en-US/docs/Web/API/ImageData/ImageData)** object.

**Comment by SHADOWELITE7** [comment]
o ok thx
