### ISSUE TITLE
observable example

### ISSUE THREAD

**Issue by timelyportfolio** [gmattie/Data-Pixels#6]
Not sure where to put this, but thought you might like to see the Mario example live in Observable.

https://beta.observablehq.com/@timelyportfolio/data-pixels-https-github-com-gmattie-data-pixels-in-observa

![image](https://user-images.githubusercontent.com/837910/42237319-0c4d5854-7ec3-11e8-8d5f-8b4d04fc322b.png)

Thanks so much for your work on this.

**Comment by gmattie** [comment]
Fun!  Very Nice, @timelyportfolio 👍 🎉 💛 

![capture](https://user-images.githubusercontent.com/933921/42243758-667c149c-7ee0-11e8-9d7d-242d5811105b.PNG)
